name: Export .pdf

on: 
  pull_request:
    branches:
      - main
      - export-action
    types:
      - ready_for_review
    paths:
      - '**.mscz'
      
jobs:
  export-pdf:
    name: Export .pdf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install MuseScore 3
        run: |
          apt update
          apt install --yes musescore3

      - name: Get changed .mscz files
        id: changed-mscz-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            *.mscz

      - name: Export each file to PDF
        run: |
          # Allow musescore to run without a GUI
          export QT_QPA_PLATFORM=offscreen

          for file in ${{ steps.changed-mscz-files.outputs.all_changed_files }}; do
            # Break the file by its extension, e.g. anonymous/andante/andante.mscz becomes [anonymous/andante/andante, mscz]
            IFS='.'
            read -a file_parts <<<"$file"

            pdf_path="${file_parts[0]}.pdf"

            musescore3 -o $pdf_path $file
          done

      # Add pdf to the PR
  